# Generated by Django 3.0.3 on 2020-07-22 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200723_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.ProcurementFiles'),
        ),
    ]
