# Generated by Django 3.0.3 on 2020-07-22 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200723_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurement',
            name='files',
        ),
        migrations.RemoveField(
            model_name='procurementfiles',
            name='file',
        ),
        migrations.AddField(
            model_name='procurement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='procurementfiles',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Procurement'),
        ),
    ]
