# Generated by Django 3.0.3 on 2020-07-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200723_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurement',
            name='file',
        ),
        migrations.AddField(
            model_name='procurementfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
