# Generated by Django 3.0.3 on 2020-07-23 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200723_0652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procurementfiles',
            old_name='files',
            new_name='procurement',
        ),
    ]
